version: '2'
services:
  web_service:
    build: ./web_service
    ports:
      - 5000:5000
    links:
      - rabbitmq
      - gateway
      - celery
    command: gunicorn -w 4 -b :5000 api:app
  celery:
    build: ./web_service
    links:
      - rabbitmq
      - gateway
    command: su -m celery -c "celery worker -l info -A api.celery"
  rabbitmq:
    image: 'rabbitmq:3.6.6-alpine'
    ports:
      - 5672:5672
  gateway:
    image: couchbase/sync-gateway
    ports:
      - 4984:4984
    volumes:
      - ./sync_gateway:/tmp/config
    command: /tmp/config/walrus_hook.json
